### PR TITLE
ElUtilitySuite: Fix?

### PR DESCRIPTION
**Pull request by nabbhacker**

### CODE REVIEW

**Comment by Nathansakoetoe** [comment]
@ChewyMoon pls check

**Comment by ChewyMoon** [comment]
no

**Comment by nabbhacker** [comment]
You can merge it, i don't see any problem in it.

**Comment by ChewyMoon** [comment]
:kappa:

**Comment by Nathansakoetoe** [comment]
Ty for BREAKING it

**Comment by Nathansakoetoe** [comment]
Abd you missed the Smite one

**Comment by nabbhacker** [comment]
:Fappa:

The smite is correct, i'm too lazy to find every exact smite name.

:roto2:

**Pull request merged**
